apiVersion: v1
kind: PersistentVolume
metadata:
  name: github-runner-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/github-runner
  storageClassName: manual  # Добавьте это поле
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-runner-pvc
  namespace: github-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual  # Добавьте это поле