apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-runner-pvc
  namespace: github-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: simple-disk  # Добавьте это поле