---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runners
  namespace: github-runner
spec:
  replicas: 1
  template:
    spec:
      repository: Dmitriy2028/Centaurea_DevOps
      labels:
        - my-custom-runner
      env: []
      containers:
      - name: github-runner
        volumeMounts:
        - mountPath: /mnt/data/github-runner
          name: github-runner-storage
      volumes:
      - name: github-runner-storage
        persistentVolumeClaim:
          claimName: github-runner-pvc