---
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: github-single-runner
  namespace: github-runner
spec:
  repository: Dmitriy2028/Centaurea_DevOps
  env: []
  containers:
  - name: github-runner
    image: summerwind/actions-runner:latest  # Укажите образ для GitHub Runner
    volumeMounts:
    - mountPath: /mnt
      name: github-runner-storage
  volumes:
  - name: github-runner-storage
    persistentVolumeClaim:
      claimName: github-runner-pvc