---
- name: Создание кластера k3d
  command: k3d cluster create mycluster \
            --api-port 192.168.100.101:36061 \
            --k3s-arg "--tls-san=192.168.100.101@server:0"
  register: k3d_create
  ignore_errors: yes

- name: Проверка статуса кластера
  command: k3d cluster list
  register: k3d_status

- name: Вывод статуса кластера
  debug:
    var: k3d_status.stdout
