---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          imagePullPolicy: Always
          image: dmitriy2028/app-test
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "50"  # Запрос на 20 миллиCPU
              memory: "128Mi"  # Запрос на 256 МБ памяти
            limits:
              cpu: "250"  # Лимит на 100 миллиCPU
              memory: "256Mi"  # Лимит на 512 МБ памяти