---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          imagePullPolicy: Always
          image: dmitriy2028/app-test
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"  # Запрос на 100 миллиCPU
              memory: "256Mi"  # Запрос на 256 МБ памяти
            limits:
              cpu: "500m"  # Лимит на 500 миллиCPU
              memory: "512Mi"  # Лимит на 512 МБ памяти