apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator-back-ingress
  namespace: app-back
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - dmitriy2028.site
    secretName: my-cert-secret
  rules:
  - host: test-back.dmitriy2028.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: calculator-back-service
            port:
              number: 8080