apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: calculator-back-hpa
  namespace: app-back
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calculator-back-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu  # Или "memory"
        target:
          type: Utilization
          averageUtilization: 70  # Целевая загрузка процессора в процентах