apiVersion: traefik.io/v1alpha1
kind: TraefikRoute
metadata:
  name: mailu-route
  namespace: mailu
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`mail.dmitriy2028.site`)
      kind: Rule
      services:
        - name: mailu-front
          port: 443
          serversTransport: mailu-web
