---
- name: Create directory for GitHub runner
  ansible.builtin.file:
    path: /mnt/data/github-runner
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create directory for local path provisioner
  ansible.builtin.file:
    path: /opt/local-path-provisioner
    state: directory
    mode: '0755'
    owner: root
    group: root
